name: style
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['jazzy']
    container:
      image: ros:${{ matrix.distro }}-ros-base
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: uncrustify
      run: /ros_entrypoint.sh ament_uncrustify ./
    - name: cpplint
      run: /ros_entrypoint.sh ament_cpplint ./